#!/bin/bash

which vi > /dev/null
if [ $? -eq 1 ]; then
    echo "Missing vim, try to install"
    sudo apt-get install vi

    if [ $? -eq 1 ]; then
        exit
    fi
fi

which git > /dev/null
if [ $? -eq 1 ]; then
    echo "Missing git, try to install"
    sudo apt-get install git
    
    if [ $? -eq 1 ]; then
        exit
    fi
fi

cd ~/bin

if [ $? -eq 1 ]; then
    echo "Making ~/bin directory"
    cd ~/
    mkdir bin
    cd bin
fi

echo "Installing self-made script"
#install SSH_Remote script
wget https://raw.githubusercontent.com/AlaudaeHong/BashScripts/master/SSH_QuickConnection/SSH_Remote
chmod +x SSH_Remote

#install SysUpdate script
wget https://raw.githubusercontent.com/AlaudaeHong/BashScripts/master/SysUpdate/SysUpdate
chmod +x SysUpdate

cd

ls .vim
if [ $? -eq 1 ]; then
    echo "Making .vim directory"
    mkdir .vim
fi

echo "Configuring VIM"
wget https://raw.githubusercontent.com/AlaudaeHong/vimrc/master/.vimrc
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall


