#!/bin/bash

cd ~/bin

if [ $? -eq 1 ]; then
    echo "Making ~/bin directory"
    cd ~/
    mkdir bin
    cd bin
fi

echo "Installing self-made script"
#install SSH_Remote script
ls ~/bin/SSH_Remote
if [ $? -eq 1 ]; then
    wget https://raw.githubusercontent.com/AlaudaeHong/BashScripts/master/SSH_QuickConnection/SSH_Remote
    chmod +x SSH_Remote
fi

#install SysUpdate script
ls ~/bin/SysUpdate
if [ $? -eq 1 ]; then
    wget https://raw.githubusercontent.com/AlaudaeHong/BashScripts/master/SysUpdate/SysUpdate
    chmod +x SysUpdate
fi

#update the system
echo "Updating System"
./SysUpdate

which vi > /dev/null
if [ $? -eq 1 ]; then
    echo "Missing vim, try to install"
    sudo apt-get install vim

    if [ $? -eq 1 ]; then
        echo "Cannot install vim....EXITING"
        exit
    fi
fi

which git > /dev/null
if [ $? -eq 1 ]; then
    echo "Missing git, try to install"
    sudo apt-get install git
    
    if [ $? -eq 1 ]; then
        echo "Cannot install git....EXITING"
        exit
    fi
fi

cd

ls .vim
if [ $? -eq 1 ]; then
    echo "Making .vim directory"
    mkdir .vim
fi

echo "Configuring VIM"
wget https://raw.githubusercontent.com/AlaudaeHong/vimrc/master/.vimrc
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall
