#!/bin/bash

rootdir="/root"
usrdir="/home/ubuntu"

ifcscope=0

#These functions need root privilege

#Parameter:
#$1: root directory
#$2: directory to be check, if not exist, create
function checkDIR {
    cd ${1}/${2} > /dev/null

    if [ $? -eq 1 ]; then
        echo "Making ${1} directory"
        mkdir ${1}/${2}
    fi
}

#Parameter
#$1: directory of installation
#$2: script to be installed
#$3: name
function install_script {
    cd $1

    rm $3
    wget https://raw.githubusercontent.com/AlaudaeHong/BashScripts/master/${2}
    chmod +x $3

    #Create a softlink for user
    if [ $1 == ${rootdir}/bin ]; then
        ln -s ${rootdir}/bin/${3} ${usrdir}/bin/${3}
    fi
}

#Parameter
#$1: package to be installed
#$2: option: silent/ask
function install_apt {
    which $1
    if [ $? -eq 1 ] && [ $2 -eq 1 ]; then
        echo "Missing ${1}, trying to install"
        apt-get install $1

        if [ $? -eq 1 ]; then
            echo "Cannot install ${1}....EXITING"
            exit
        fi
    fi
}

function config_vim {

    echo "Configuring VIM"

    cd $rootdir
    rm .vimrc
    wget https://raw.githubusercontent.com/AlaudaeHong/vimrc/master/.vimrc
    git clone https://github.com/VundleVim/Vundle.vim.git ${rootdir}/.vim/bundle/Vundle.vim

    if [ $usrdir != $rootdir ]; then
        cd $usrdir

            rm .vimrc
        wget https://raw.githubusercontent.com/AlaudaeHong/vimrc/master/.vimrc
        git clone https://github.com/VundleVim/Vundle.vim.git ${usrdir}/.vim/bundle/Vundle.vim
    fi

    vim +PluginInstall +qall
}

echo "Making directorys"
checkDIR /root bin
checkDIR /root .vim

if [ $usrdir == $rootdir ]; then
    checkDIR ~ bin
    checkDIR ~ .vim
fi

echo "Installing self-made script"

#For root user
install_script $rootdir/bin SysUpdate/SysUpdate SysUpdate

#For normal user
install_script $usrdir/bin SSH_QuickConnection/SSH_Remote SSH_Remote

#Source .profile again
source ~/.bash_profile

#update the system
echo "Updating System"
SysUpdate

#Install VIM
install_apt     vim     1

#Install Git
install_apt     git     1

#Dependency for VIM plugin Tagbar
install_apt     ctags   1

#Option of CScope
install_apt     cscope  $ifcscope

config_vim
