#!/bin/bash
  
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y
sudo apt-get autoremove -y
sudo apt-get autoclean -y

pip install -U git+https://github.com/shadowsocks/shadowsocks.git@master
